# Generated by Django 3.1.2 on 2022-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testingModel',
        ),
    ]
